.TH "ev_poller" 3 "24 Nov 2008" "Version 0" "events" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ev_poller \- 
.SH SYNOPSIS
.br
.PP
\fC#include <events.h>\fP
.PP
.SH "Detailed Description"
.PP 
poller functions pointer 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for events from the source code.
